// AQUI SE ADMINISTRARA LA INFORMACION DE LOS ALUMNOS, PARA SATISFACER LOS REQUISITOS DEL PROYECTO, AGREGO: NOMBRES, APELLIDOS y COMO EXTRAS SE AGRAGO UN "ID o CODIGO" 
// DEL ALUMNO Y UNA FOTOGRAFIA.

// Se uso la constante de "Students" haciendo referencia a los estudiantes.
// Las calificaciones 1,2 y 3 hacen referencia a la calificacion final de dichas materias.
const students = [
    {"codigo":"12301",
    "nombres":"Vania",
    "apellidos":"Madrigal",
    "edad":"23",
    "mat1":"Historia",
    "mat2":"Geografia",
    "mat3": "Finanzas",
    "cal1": 45,
    "cal2": 50,
    "cal3": 49, 
    "foto":"https://i1.wp.com/www.shelbytrailer.com/wp-content/uploads/2017/03/person-generic.jpg?ssl=1",
    },

    {"codigo":"12302",
    "nombres":"Eduardo",
    "apellidos":"Vergara",
    "edad":"27",
    "mat1":"Calculo",
    "mat2":"Geografia",
    "mat3": "Finanzas",
    "cal1": 35,
    "cal2": 37,
    "cal3": 40, 
    "foto":"https://i1.wp.com/www.shelbytrailer.com/wp-content/uploads/2017/03/person-generic.jpg?ssl=1",
    },

    {"codigo":"12303",
    "nombres":"Jose",
    "apellidos":"Perez",
    "edad":"22",
    "mat1":"Comunicacion",
    "mat2":"Diseño",
    "mat3": "Aviacion",
    "cal1": 45,
    "cal2": 42,
    "cal3": 39, 
    "foto":"https://i1.wp.com/www.shelbytrailer.com/wp-content/uploads/2017/03/person-generic.jpg?ssl=1",
    },

    {"codigo":"12304",
    "nombres":"Emma",
    "apellidos":"Regalado",
    "edad":"25",
    "mat1":"Matematicas",
    "mat2":"Geografia",
    "mat3": "Aviacion",
    "cal1": 40,
    "cal2": 39,
    "cal3": 45, 
    "foto":"https://i1.wp.com/www.shelbytrailer.com/wp-content/uploads/2017/03/person-generic.jpg?ssl=1",
    },

    {"codigo":"12305",
    "nombres":"Daniel",
    "apellidos":"Velazco",
    "edad":"30",
    "mat1":"Finanzas",
    "mat2":"Geografia",
    "mat3": "Comunicacion",
    "cal1": 40,
    "cal2": 39,
    "cal3": 44, 
    "foto":"https://i1.wp.com/www.shelbytrailer.com/wp-content/uploads/2017/03/person-generic.jpg?ssl=1",
    },

    {"codigo":"12306",
    "nombres":"Armando",
    "apellidos":"Paredes",
    "edad":"26",
    "mat1":"Meteorologia",
    "mat2":"Comunicacion",
    "mat3": "Humanidades",
    "cal1": 37,
    "cal2": 42,
    "cal3": 40, 
    "foto":"https://i1.wp.com/www.shelbytrailer.com/wp-content/uploads/2017/03/person-generic.jpg?ssl=1",
    },
    
    {"codigo":"12307",
    "nombres":"Martha",
    "apellidos":"Bucio",
    "edad":"55",
    "mat1":"Meteorologia",
    "mat2":"Diseño",
    "mat3": "Aviacion",
    "cal1": 44,
    "cal2": 46,
    "cal3": 40, 
    "foto":"https://i1.wp.com/www.shelbytrailer.com/wp-content/uploads/2017/03/person-generic.jpg?ssl=1",
    },

    {"codigo":"12308",
    "nombres":"Alejandro",
    "apellidos":"Mercado",
    "edad":"26",
    "mat1":"Religion",
    "mat2":"Matematicas",
    "mat3": "Aviacion",
    "cal1": 39,
    "cal2": 40,
    "cal3": 42, 
    "foto":"https://i1.wp.com/www.shelbytrailer.com/wp-content/uploads/2017/03/person-generic.jpg?ssl=1",
    },
]
